export const PAISES = [
  { codigo: "AF", nome: "Afeganistão", bandeira: "🇦🇫" },
  { codigo: "ZA", nome: "África do Sul", bandeira: "🇿🇦" },
  { codigo: "AL", nome: "Albânia", bandeira: "🇦🇱" },
  { codigo: "DE", nome: "Alemanha", bandeira: "🇩🇪" },
  { codigo: "AD", nome: "Andorra", bandeira: "🇦🇩" },
  { codigo: "AO", nome: "Angola", bandeira: "🇦🇴" },
  { codigo: "AG", nome: "Antígua e Barbuda", bandeira: "🇦🇬" },
  { codigo: "SA", nome: "Arábia Saudita", bandeira: "🇸🇦" },
  { codigo: "DZ", nome: "Argélia", bandeira: "🇩🇿" },
  { codigo: "AR", nome: "Argentina", bandeira: "🇦🇷" },
  { codigo: "AM", nome: "Arménia", bandeira: "🇦🇲" },
  { codigo: "AU", nome: "Austrália", bandeira: "🇦🇺" },
  { codigo: "AT", nome: "Áustria", bandeira: "🇦🇹" },
  { codigo: "AZ", nome: "Azerbaijão", bandeira: "🇦🇿" },
  { codigo: "BS", nome: "Bahamas", bandeira: "🇧🇸" },
  { codigo: "BD", nome: "Bangladexe", bandeira: "🇧🇩" },
  { codigo: "BB", nome: "Barbados", bandeira: "🇧🇧" },
  { codigo: "BH", nome: "Barém", bandeira: "🇧🇭" },
  { codigo: "BE", nome: "Bélgica", bandeira: "🇧🇪" },
  { codigo: "BZ", nome: "Belize", bandeira: "🇧🇿" },
  { codigo: "BJ", nome: "Benim", bandeira: "🇧🇯" },
  { codigo: "BY", nome: "Bielorrússia", bandeira: "🇧🇾" },
  { codigo: "BO", nome: "Bolívia", bandeira: "🇧🇴" },
  { codigo: "BA", nome: "Bósnia e Herzegovina", bandeira: "🇧🇦" },
  { codigo: "BW", nome: "Botsuana", bandeira: "🇧🇼" },
  { codigo: "BR", nome: "Brasil", bandeira: "🇧🇷" },
  { codigo: "BN", nome: "Brunei", bandeira: "🇧🇳" },
  { codigo: "BG", nome: "Bulgária", bandeira: "🇧🇬" },
  { codigo: "BF", nome: "Burquina Faso", bandeira: "🇧🇫" },
  { codigo: "BI", nome: "Burúndi", bandeira: "🇧🇮" },
  { codigo: "BT", nome: "Butão", bandeira: "🇧🇹" },
  { codigo: "CV", nome: "Cabo Verde", bandeira: "🇨🇻" },
  { codigo: "CM", nome: "Camarões", bandeira: "🇨🇲" },
  { codigo: "KH", nome: "Camboja", bandeira: "🇰🇭" },
  { codigo: "CA", nome: "Canadá", bandeira: "🇨🇦" },
  { codigo: "QA", nome: "Catar", bandeira: "🇶🇦" },
  { codigo: "KZ", nome: "Cazaquistão", bandeira: "🇰🇿" },
  { codigo: "TD", nome: "Chade", bandeira: "🇹🇩" },
  { codigo: "CL", nome: "Chile", bandeira: "🇨🇱" },
  { codigo: "CN", nome: "China", bandeira: "🇨🇳" },
  { codigo: "CY", nome: "Chipre", bandeira: "🇨🇾" },
  { codigo: "CO", nome: "Colômbia", bandeira: "🇨🇴" },
  { codigo: "KM", nome: "Comores", bandeira: "🇰🇲" },
  { codigo: "CG", nome: "Congo", bandeira: "🇨🇬" },
  { codigo: "CD", nome: "Congo (RDC)", bandeira: "🇨🇩" },
  { codigo: "KR", nome: "Coreia do Sul", bandeira: "🇰🇷" },
  { codigo: "KP", nome: "Coreia do Norte", bandeira: "🇰🇵" },
  { codigo: "CI", nome: "Costa do Marfim", bandeira: "🇨🇮" },
  { codigo: "CR", nome: "Costa Rica", bandeira: "🇨🇷" },
  { codigo: "HR", nome: "Croácia", bandeira: "🇭🇷" },
  { codigo: "CU", nome: "Cuba", bandeira: "🇨🇺" },
  { codigo: "DK", nome: "Dinamarca", bandeira: "🇩🇰" },
  { codigo: "DJ", nome: "Djibuti", bandeira: "🇩🇯" },
  { codigo: "DM", nome: "Dominica", bandeira: "🇩🇲" },
  { codigo: "EG", nome: "Egito", bandeira: "🇪🇬" },
  { codigo: "SV", nome: "El Salvador", bandeira: "🇸🇻" },
  { codigo: "AE", nome: "Emirados Árabes Unidos", bandeira: "🇦🇪" },
  { codigo: "EC", nome: "Equador", bandeira: "🇪🇨" },
  { codigo: "ER", nome: "Eritreia", bandeira: "🇪🇷" },
  { codigo: "SK", nome: "Eslováquia", bandeira: "🇸🇰" },
  { codigo: "SI", nome: "Eslovénia", bandeira: "🇸🇮" },
  { codigo: "ES", nome: "Espanha", bandeira: "🇪🇸" },
  { codigo: "US", nome: "Estados Unidos", bandeira: "🇺🇸" },
  { codigo: "EE", nome: "Estónia", bandeira: "🇪🇪" },
  { codigo: "SZ", nome: "Essuatíni", bandeira: "🇸🇿" },
  { codigo: "ET", nome: "Etiópia", bandeira: "🇪🇹" },
  { codigo: "FJ", nome: "Fiji", bandeira: "🇫🇯" },
  { codigo: "PH", nome: "Filipinas", bandeira: "🇵🇭" },
  { codigo: "FI", nome: "Finlândia", bandeira: "🇫🇮" },
  { codigo: "FR", nome: "França", bandeira: "🇫🇷" },
  { codigo: "GA", nome: "Gabão", bandeira: "🇬🇦" },
  { codigo: "GM", nome: "Gâmbia", bandeira: "🇬🇲" },
  { codigo: "GH", nome: "Gana", bandeira: "🇬🇭" },
  { codigo: "GE", nome: "Geórgia", bandeira: "🇬🇪" },
  { codigo: "GD", nome: "Granada", bandeira: "🇬🇩" },
  { codigo: "GR", nome: "Grécia", bandeira: "🇬🇷" },
  { codigo: "GT", nome: "Guatemala", bandeira: "🇬🇹" },
  { codigo: "GY", nome: "Guiana", bandeira: "🇬🇾" },
  { codigo: "GN", nome: "Guiné", bandeira: "🇬🇳" },
  { codigo: "GQ", nome: "Guiné Equatorial", bandeira: "🇬🇶" },
  { codigo: "GW", nome: "Guiné-Bissau", bandeira: "🇬🇼" },
  { codigo: "HT", nome: "Haiti", bandeira: "🇭🇹" },
  { codigo: "HN", nome: "Honduras", bandeira: "🇭🇳" },
  { codigo: "HU", nome: "Hungria", bandeira: "🇭🇺" },
  { codigo: "YE", nome: "Iémen", bandeira: "🇾🇪" },
  { codigo: "IN", nome: "Índia", bandeira: "🇮🇳" },
  { codigo: "ID", nome: "Indonésia", bandeira: "🇮🇩" },
  { codigo: "IQ", nome: "Iraque", bandeira: "🇮🇶" },
  { codigo: "IR", nome: "Irão", bandeira: "🇮🇷" },
  { codigo: "IE", nome: "Irlanda", bandeira: "🇮🇪" },
  { codigo: "IS", nome: "Islândia", bandeira: "🇮🇸" },
  { codigo: "IL", nome: "Israel", bandeira: "🇮🇱" },
  { codigo: "IT", nome: "Itália", bandeira: "🇮🇹" },
  { codigo: "JM", nome: "Jamaica", bandeira: "🇯🇲" },
  { codigo: "JP", nome: "Japão", bandeira: "🇯🇵" },
  { codigo: "JO", nome: "Jordânia", bandeira: "🇯🇴" },
  { codigo: "KW", nome: "Koweit", bandeira: "🇰🇼" },
  { codigo: "LA", nome: "Laos", bandeira: "🇱🇦" },
  { codigo: "LS", nome: "Lesoto", bandeira: "🇱🇸" },
  { codigo: "LV", nome: "Letónia", bandeira: "🇱🇻" },
  { codigo: "LB", nome: "Líbano", bandeira: "🇱🇧" },
  { codigo: "LR", nome: "Libéria", bandeira: "🇱🇷" },
  { codigo: "LY", nome: "Líbia", bandeira: "🇱🇾" },
  { codigo: "LI", nome: "Listenstaine", bandeira: "🇱🇮" },
  { codigo: "LT", nome: "Lituânia", bandeira: "🇱🇹" },
  { codigo: "LU", nome: "Luxemburgo", bandeira: "🇱🇺" },
  { codigo: "MK", nome: "Macedónia do Norte", bandeira: "🇲🇰" },
  { codigo: "MG", nome: "Madagáscar", bandeira: "🇲🇬" },
  { codigo: "MY", nome: "Malásia", bandeira: "🇲🇾" },
  { codigo: "MW", nome: "Maláui", bandeira: "🇲🇼" },
  { codigo: "MV", nome: "Maldivas", bandeira: "🇲🇻" },
  { codigo: "ML", nome: "Mali", bandeira: "🇲🇱" },
  { codigo: "MT", nome: "Malta", bandeira: "🇲🇹" },
  { codigo: "MA", nome: "Marrocos", bandeira: "🇲🇦" },
  { codigo: "MU", nome: "Maurícia", bandeira: "🇲🇺" },
  { codigo: "MR", nome: "Mauritânia", bandeira: "🇲🇷" },
  { codigo: "MX", nome: "México", bandeira: "🇲🇽" },
  { codigo: "MM", nome: "Mianmar", bandeira: "🇲🇲" },
  { codigo: "FM", nome: "Micronésia", bandeira: "🇫🇲" },
  { codigo: "MZ", nome: "Moçambique", bandeira: "🇲🇿" },
  { codigo: "MD", nome: "Moldávia", bandeira: "🇲🇩" },
  { codigo: "MC", nome: "Mónaco", bandeira: "🇲🇨" },
  { codigo: "MN", nome: "Mongólia", bandeira: "🇲🇳" },
  { codigo: "ME", nome: "Montenegro", bandeira: "🇲🇪" },
  { codigo: "NA", nome: "Namíbia", bandeira: "🇳🇦" },
  { codigo: "NR", nome: "Nauru", bandeira: "🇳🇷" },
  { codigo: "NP", nome: "Nepal", bandeira: "🇳🇵" },
  { codigo: "NI", nome: "Nicarágua", bandeira: "🇳🇮" },
  { codigo: "NE", nome: "Níger", bandeira: "🇳🇪" },
  { codigo: "NG", nome: "Nigéria", bandeira: "🇳🇬" },
  { codigo: "NO", nome: "Noruega", bandeira: "🇳🇴" },
  { codigo: "NZ", nome: "Nova Zelândia", bandeira: "🇳🇿" },
  { codigo: "OM", nome: "Omã", bandeira: "🇴🇲" },
  { codigo: "NL", nome: "Países Baixos", bandeira: "🇳🇱" },
  { codigo: "PW", nome: "Palau", bandeira: "🇵🇼" },
  { codigo: "PA", nome: "Panamá", bandeira: "🇵🇦" },
  { codigo: "PG", nome: "Papua Nova Guiné", bandeira: "🇵🇬" },
  { codigo: "PK", nome: "Paquistão", bandeira: "🇵🇰" },
  { codigo: "PY", nome: "Paraguai", bandeira: "🇵🇾" },
  { codigo: "PE", nome: "Peru", bandeira: "🇵🇪" },
  { codigo: "PL", nome: "Polónia", bandeira: "🇵🇱" },
  { codigo: "PT", nome: "Portugal", bandeira: "🇵🇹" },
  { codigo: "KE", nome: "Quénia", bandeira: "🇰🇪" },
  { codigo: "KG", nome: "Quirguistão", bandeira: "🇰🇬" },
  { codigo: "GB", nome: "Reino Unido", bandeira: "🇬🇧" },
  { codigo: "CF", nome: "República Centro-Africana", bandeira: "🇨🇫" },
  { codigo: "DO", nome: "República Dominicana", bandeira: "🇩🇴" },
  { codigo: "CZ", nome: "República Checa", bandeira: "🇨🇿" },
  { codigo: "RO", nome: "Roménia", bandeira: "🇷🇴" },
  { codigo: "RW", nome: "Ruanda", bandeira: "🇷🇼" },
  { codigo: "RU", nome: "Rússia", bandeira: "🇷🇺" },
  { codigo: "WS", nome: "Samoa", bandeira: "🇼🇸" },
  { codigo: "SM", nome: "San Marino", bandeira: "🇸🇲" },
  { codigo: "LC", nome: "Santa Lúcia", bandeira: "🇱🇨" },
  { codigo: "KN", nome: "São Cristóvão e Neves", bandeira: "🇰🇳" },
  { codigo: "ST", nome: "São Tomé e Príncipe", bandeira: "🇸🇹" },
  { codigo: "VC", nome: "São Vicente e Granadinas", bandeira: "🇻🇨" },
  { codigo: "SN", nome: "Senegal", bandeira: "🇸🇳" },
  { codigo: "SL", nome: "Serra Leoa", bandeira: "🇸🇱" },
  { codigo: "RS", nome: "Sérvia", bandeira: "🇷🇸" },
  { codigo: "SC", nome: "Seicheles", bandeira: "🇸🇨" },
  { codigo: "SG", nome: "Singapura", bandeira: "🇸🇬" },
  { codigo: "SY", nome: "Síria", bandeira: "🇸🇾" },
  { codigo: "SO", nome: "Somália", bandeira: "🇸🇴" },
  { codigo: "LK", nome: "Sri Lanca", bandeira: "🇱🇰" },
  { codigo: "SE", nome: "Suécia", bandeira: "🇸🇪" },
  { codigo: "CH", nome: "Suíça", bandeira: "🇨🇭" },
  { codigo: "SD", nome: "Sudão", bandeira: "🇸🇩" },
  { codigo: "SS", nome: "Sudão do Sul", bandeira: "🇸🇸" },
  { codigo: "SR", nome: "Suriname", bandeira: "🇸🇷" },
  { codigo: "TH", nome: "Tailândia", bandeira: "🇹🇭" },
  { codigo: "TW", nome: "Taiwan", bandeira: "🇹🇼" },
  { codigo: "TJ", nome: "Tajiquistão", bandeira: "🇹🇯" },
  { codigo: "TZ", nome: "Tanzânia", bandeira: "🇹🇿" },
  { codigo: "TL", nome: "Timor-Leste", bandeira: "🇹🇱" },
  { codigo: "TG", nome: "Togo", bandeira: "🇹🇬" },
  { codigo: "TO", nome: "Tonga", bandeira: "🇹🇴" },
  { codigo: "TT", nome: "Trindade e Tobago", bandeira: "🇹🇹" },
  { codigo: "TN", nome: "Tunísia", bandeira: "🇹🇳" },
  { codigo: "TM", nome: "Turquemenistão", bandeira: "🇹🇲" },
  { codigo: "TR", nome: "Turquia", bandeira: "🇹🇷" },
  { codigo: "TV", nome: "Tuvalu", bandeira: "🇹🇻" },
  { codigo: "UA", nome: "Ucrânia", bandeira: "🇺🇦" },
  { codigo: "UG", nome: "Uganda", bandeira: "🇺🇬" },
  { codigo: "UY", nome: "Uruguai", bandeira: "🇺🇾" },
  { codigo: "UZ", nome: "Usbequistão", bandeira: "🇺🇿" },
  { codigo: "VU", nome: "Vanuatu", bandeira: "🇻🇺" },
  { codigo: "VA", nome: "Vaticano", bandeira: "🇻🇦" },
  { codigo: "VE", nome: "Venezuela", bandeira: "🇻🇪" },
  { codigo: "VN", nome: "Vietname", bandeira: "🇻🇳" },
  { codigo: "ZM", nome: "Zâmbia", bandeira: "🇿🇲" },
  { codigo: "ZW", nome: "Zimbábue", bandeira: "🇿🇼" },
];
